### PR TITLE
adding support for globbing 10-day periods

### PR DESCRIPTION
**Pull request by pboocock**
Please review and let me know if any changes need to be made. Would love to get this into the main branch of the project, rather than having us run off my fork.

### CODE REVIEW

**Comment by pboocock** [comment]
@davidmarin Please review and see if this is something you'd like to include in the main package.

**Comment by irskep** [comment]
I'm not Dave, but having some idea of what he would say:

1. Bumping the package version number in a feature pull request is a very bold move
2. Needs tests
3. Clever use of release note dates!

**Comment by davidmarin** [comment]
Oh, nice! You're the first person, in what, 5 years to add a feature to this library without expanding its scope. Converging on perfection here. ;)

Yeah, mostly, please add tests. I apologize for making you install `testify`, but it's pretty straightforward if you understand `unittest`, and there are other tests you can use as an example.

Clearly this won't go into 0.1 (already released), but `0.2.dev0` would be a more appropriate version number.

**Comment by pboocock** [comment]
Ok, I added some test cases that forced some improvements in the rest of my changes, and cleaned up the version number.

**Comment by pboocock** [comment]
@davidmarin @irskep thanks for the tips guys. would love to be able to get this out asap so that we can point to the main package in our code instead of this side repo i'm managing.

**Comment by davidmarin** [comment]
Huh. There are definitely simpler ways to code this, but your approach works.

**Comment by pboocock** [comment]
OK great thanks. Is this going to go up on PyPi as well?

**Comment by davidmarin** [comment]
Just got version 0.2 up on PyPI. For some reason I couldn't upload it with the command-line tools (maybe because the previous release is so old?). Enjoy.

**Comment by pboocock** [comment]
Awesome thanks!

**Pull request merged**
